### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Jiangjiayi1016** [ViennaTools/ViennaEMC#2]
Would it be possible to tell me the bibliography of this software? Especially the iterative formula used when solving Poisson's equation with SOR method, because I saw the notes "theses eq. 4.11" and "theses eq. 4.12" in the code.

**Comment by Jiangjiayi1016** [comment]
@RobinSteiner

**Comment by RobinSteiner** [comment]
We will come back to you as soon as possible, but have to clarify this internally first.

**Comment by FilipovicLado** [comment]
You can take a look at the thesis (attached) from a previous colleague, which describes the SOR method. This was implemented in a previous version of the code, which is bundled with ViennaWD (https://viennawd.sourceforge.net/).
[Marek_Thesis.pdf](https://github.com/ViennaTools/ViennaEMC/files/10918506/Marek_Thesis.pdf)

**Comment by Jiangjiayi1016** [comment]
Thank you very much. it helps me a lot. I will study it carefully！

**Comment by Jiangjiayi1016** [comment]
May I ask why the expression for the output potential is “(Eg/2-potential)*Vt”?If this is the true potential, why is there no negative sign when calculating the electric field？
@FilipovicLado

**Comment by Jiangjiayi1016** [comment]
@RobinSteiner
